# Generated by Django 2.2.6 on 2019-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapp',
            old_name='created_at',
            new_name='lastupdated',
        ),
        migrations.RemoveField(
            model_name='loanapp',
            name='body',
        ),
        migrations.RemoveField(
            model_name='loanapp',
            name='title',
        ),
        migrations.AddField(
            model_name='loanapp',
            name='business',
            field=models.TextField(default='defaultValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapp',
            name='cfapplicationdata',
            field=models.TextField(default='defaultValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapp',
            name='owners',
            field=models.TextField(default='defaultValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapp',
            name='requestheader',
            field=models.TextField(default='defaultValue'),
            preserve_default=False,
        ),
    ]
