# Generated by Django 2.2.6 on 2019-10-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191011_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapp',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='loanapp',
            old_name='cfapplicationdata',
            new_name='CFApplicationData',
        ),
        migrations.RenameField(
            model_name='loanapp',
            old_name='owners',
            new_name='Owners',
        ),
        migrations.RenameField(
            model_name='loanapp',
            old_name='requestheader',
            new_name='RequestHeader',
        ),
    ]
